version: '3.8'

services:
  db-l2:
    image: postgres:14
    restart: always
    container_name: 'postgres-l2'
    command: postgres -c 'max_connections=500'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgresl2'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7433:5432
    volumes:
      - ./blockscout-db-data-l2:/var/lib/postgresql/data/
